const FETCH_TODO_BEGIN = "FETCH_TODO_BEGIN";
const FETCH_TODO_SUCCESS = "FETCH_TODO_SUCCESS";
const FETCH_TODO_ERROR = "FETCH_TODO_ERROR";
const ADD_TODO = "ADD_TODO";
const EDIT_TODO = "EDIT_TODO";
const DELETE_TODO = "DELETE_TODO";

export {
  FETCH_TODO_SUCCESS,
  FETCH_TODO_ERROR,
  FETCH_TODO_BEGIN,
  ADD_TODO,
  EDIT_TODO,
  DELETE_TODO,
};
